/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119449-g1b643e3f65-20250508"
#endif /* AVUTIL_FFVERSION_H */
